-- Drawer — initial schema.
-- Applied automatically by the postgres image on first boot of an empty volume.
-- Once real data exists, use dbmate/node-pg-migrate for changes; do not edit this file.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- A single monotonic revision counter shared by every synced table.
-- The sync cursor is a value of THIS sequence, never a wall-clock timestamp:
-- two rows written in the same millisecond would straddle a time cursor and one
-- would be skipped forever. A sequence cannot do that.
CREATE SEQUENCE drawer_rev_seq;

CREATE TYPE item_kind AS ENUM ('image', 'video', 'audio', 'document', 'link', 'text');

CREATE TABLE users (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email       text UNIQUE,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Single-user deployment: one fixed owner, seeded here so nothing has to
-- bootstrap it at runtime. Multi-user later is additive — every row below is
-- already owner-scoped.
INSERT INTO users (id, email) VALUES ('00000000-0000-0000-0000-000000000001', NULL);

-- Content-addressed binary objects. One row per distinct byte sequence, ever.
CREATE TABLE blobs (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sha256       bytea NOT NULL UNIQUE,
  byte_size    bigint NOT NULL CHECK (byte_size >= 0),
  mime_type    text NOT NULL,
  storage_key  text NOT NULL,          -- blobs/<ab>/<cd>/<hex>
  thumb_key    text,                   -- derived webp, 512px long edge
  width        int,
  height       int,
  duration_ms  int,
  page_count   int,
  uploaded_at  timestamptz,            -- NULL until the client commits the upload
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE categories (
  id          uuid PRIMARY KEY,
  owner_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name        text NOT NULL CHECK (length(btrim(name)) > 0),
  color       text CHECK (color ~ '^#[0-9a-fA-F]{6}$'),
  icon        text,
  sort_order  int NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  rev         bigint NOT NULL DEFAULT nextval('drawer_rev_seq')
);

-- Expression uniqueness has to be an index, not a table constraint. Scoped to
-- live rows so a name can be reused after its category is deleted.
CREATE UNIQUE INDEX categories_owner_name_uniq
  ON categories (owner_id, lower(name)) WHERE deleted_at IS NULL;

CREATE TABLE items (
  id            uuid PRIMARY KEY,      -- uuidv7, generated ON THE CLIENT so capture works offline
  owner_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind          item_kind NOT NULL,
  title         text,
  note          text,
  blob_id       uuid REFERENCES blobs(id),

  -- kind = 'link'
  url                 text,
  link_title          text,
  link_description    text,
  link_site_name      text,
  link_image_blob_id  uuid REFERENCES blobs(id),

  body            text,                -- kind = 'text'
  extracted_text  text,                -- PDF text layer (OCR would land here too)

  source_app    text,                  -- referring package, e.g. com.instagram.android
  captured_at   timestamptz NOT NULL,  -- when YOU shared it
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  deleted_at    timestamptz,
  rev           bigint NOT NULL DEFAULT nextval('drawer_rev_seq'),
  tags          text[] NOT NULL DEFAULT '{}',

  search tsvector GENERATED ALWAYS AS (
      setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
      setweight(to_tsvector('simple', coalesce(link_title, '')), 'A') ||
      setweight(to_tsvector('simple', coalesce(note, '')), 'B') ||
      setweight(to_tsvector('simple', coalesce(link_description, '')), 'C') ||
      setweight(to_tsvector('simple', coalesce(body, '')), 'C') ||
      setweight(to_tsvector('simple', coalesce(extracted_text, '')), 'D')
  ) STORED,

  -- A link needs a url; anything with bytes needs a blob. Cheap guard against
  -- half-formed rows arriving from a buggy client.
  CONSTRAINT items_link_has_url CHECK (kind <> 'link' OR url IS NOT NULL),
  CONSTRAINT items_text_has_body CHECK (kind <> 'text' OR body IS NOT NULL)
);

-- Many-to-many: an item can live in several categories. Not separately synced —
-- an item's category set travels with the item and bumps the item's rev.
CREATE TABLE item_categories (
  item_id     uuid NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  category_id uuid NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  PRIMARY KEY (item_id, category_id)
);

CREATE TABLE devices (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name          text NOT NULL,
  token_hash    bytea NOT NULL UNIQUE,  -- sha256 of the opaque device token
  created_at    timestamptz NOT NULL DEFAULT now(),
  last_seen_at  timestamptz,
  revoked_at    timestamptz
);

-- One-shot enrollment codes, printed by the server and typed into the app once.
CREATE TABLE enroll_codes (
  code        text PRIMARY KEY,
  owner_id    uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at  timestamptz NOT NULL,
  used_at     timestamptz
);

CREATE INDEX items_owner_captured_idx ON items (owner_id, captured_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX items_owner_rev_idx      ON items (owner_id, rev);
CREATE INDEX items_search_idx         ON items USING GIN (search);
CREATE INDEX items_tags_idx           ON items USING GIN (tags);
CREATE INDEX items_blob_idx           ON items (blob_id) WHERE blob_id IS NOT NULL;
CREATE INDEX categories_owner_rev_idx ON categories (owner_id, rev);
CREATE INDEX item_categories_cat_idx  ON item_categories (category_id, item_id);

-- Every mutation advances the shared revision counter and stamps updated_at, so
-- the sync endpoint never depends on clients getting either right.
CREATE OR REPLACE FUNCTION drawer_bump_rev() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  NEW.rev := nextval('drawer_rev_seq');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER items_bump_rev BEFORE UPDATE ON items
  FOR EACH ROW EXECUTE FUNCTION drawer_bump_rev();
CREATE TRIGGER categories_bump_rev BEFORE UPDATE ON categories
  FOR EACH ROW EXECUTE FUNCTION drawer_bump_rev();

-- Default categories so the app is never an empty grid on first run.
INSERT INTO categories (id, owner_id, name, icon, sort_order) VALUES
  ('00000000-0000-0000-0000-0000000000a1', '00000000-0000-0000-0000-000000000001', 'Inbox',   '📥', 0),
  ('00000000-0000-0000-0000-0000000000a2', '00000000-0000-0000-0000-000000000001', 'Memes',   '😂', 1),
  ('00000000-0000-0000-0000-0000000000a3', '00000000-0000-0000-0000-000000000001', 'Read later', '📖', 2),
  ('00000000-0000-0000-0000-0000000000a4', '00000000-0000-0000-0000-000000000001', 'Reference',  '📎', 3);
